### ISSUE TITLE
JS-style sourcemaps in CSS

### ISSUE THREAD

**Issue by jamesarosen** [ef4/broccoli-sourcemap-concat#37]
If I try to add sourcemaps support for CSS:

``` js
app.options.sourcemaps = {
  enabled: true,
  extensions: [ 'js', 'css' ]
};
```

then my CSS looks like

``` css
div {
  color: blue;
}
//# sourceMappingURL=test-support.css.map
```

This is not valid CSS. According to the [proposal](https://docs.google.com/document/d/1U1RGAehQwRypUTovF1KRlpiOFze0b-_2gc6fAH0KY0k/edit#), it should probably be

``` css
div {
  color: blue;
}
/*# sourceMappingURL=test-support.css.map */
```

Found because of https://github.com/postcss/autoprefixer/issues/606
